### ISSUE TITLE
Evaluate the possibility of adding ionic to support behat mobile app testing

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-docker#101]
Basically this is about to incorporate https://github.com/moodlehq/moodle-ci-runner/pull/2 here, trying to keep features on par when reasonable.

Surely controlled by some ```MOODLE_DOCKER_IONIC``` env var or similar.

Ciao :-)

**Comment by NeillM** [comment]
Seems to work fine. I have put up a pull request #122 

Tested it on Windows and against Linux on our Jenkins server

**Comment by stronk7** [comment]
Closing this now that #122 has been merged, thanks!
