### ISSUE TITLE
Quoted arguments not preserved (--name)

### ISSUE THREAD

**Issue by paulholden** [moodlehq/moodle-docker#106]
I'm trying a Behat run passing the `--name` argument (so I can run individual scenarios, rather than entire feature files), but get the following error:

```
$ bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --name="Navigate action menu"
Running single behat site:

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  Too many arguments, expected arguments "paths".         
                                                          

behat [-s|--suite SUITE] [-f|--format FORMAT] [-o|--out OUT] [--format-settings FORMAT-SETTINGS] [--init] [--lang LANG] [--name NAME] [--tags TAGS] [--role ROLE] [--story-syntax] [-d|--definitions DEFINITIONS] [--snippets-for [SNIPPETS-FOR]] [--snippets-type SNIPPETS-TYPE] [--append-snippets] [--no-snippets] [--strict] [--order ORDER] [--skip-passed] [--rerun] [--stop-on-failure] [--dry-run] [--] [<paths>]

To re-run failed processes, you can use following command:
php admin/tool/behat/cli/run.php --name="Navigate" 'action' 'menu' --rerun
```

**Comment by stronk7** [comment]
Hi Paul, maybe you can try it with #109 applied (it's really simple change) and report there? it's basically the same fix that we had to apply to our other "caller" (moodle-ci-runner) recently and seems to make the trick here.

Pity I don't have any windows at hand to determine if the ```bin/moodle-docker-compose.cmd`` CMD is exposed to the same problem.

Ciao :-)

**Comment by christianwolters** [comment]
Hi,

I just tried it on windows, calling --name "Browse by category" and it started.
Used both, Standard cmd as well as cmder (https://cmder.net/).

Cheers,
Christian

PS: Probably not relevant here, but the suite fails on my site.

**Comment by stronk7** [comment]
Aha, thanks @christianwolters! So it seems that the problem doesn't exist under windows and it ran "ok" (you were able to see the dots and a "precious" "F", I assume).

Not really sure why it failed as far as the docker env should be pretty much the same once compose has make its job creating all the containers and so on.

Thanks!

**Comment by christianwolters** [comment]
> So it seems that the problem doesn't exist under windows and it ran "ok" (you were able to see the dots and a "precious" "F", I assume).

Yes, exactly...

> Not really sure why it failed as far as the docker env should be pretty much the same once compose has make its job creating all the containers and so on.

... me neither, but I was in a hurry so I may have mounted the wrong moodle source.

Have a good start into the week!

**Comment by paulholden** [comment]
> Hi Paul, maybe you can try it with #109 applied (it's really simple change) and report there?

Thank you @stronk7 - this change did indeed fix the problem I had with quoted arguments
