### ISSUE TITLE
Add remarks for XDebug usage to README

### ISSUE THREAD

**Issue by christianwolters** [moodlehq/moodle-docker#118]
Hi,

I'd like to propose an enhancement for the README.

@abias recently documented in
https://github.com/moodlehq/moodle-php-apache/issues/17#issuecomment-581877394
how to add XDebug to a running webserver container via local bash script
and commands for dis/enabling XDebug on the fly.

IMHO it would be very useful to add these remarks to the README of this repo,
do you agree?

Cheers
Christian

**Comment by abias** [comment]
Hi @christianwolters ,

I think this is a good proposal.
I have created a pull request to add these commands to the README.

Cheers,
Alex
