### ISSUE TITLE
Prerequisite for moodle code missing

### ISSUE THREAD

**Issue by Lyannic** [moodlehq/moodle-docker#123]
It would be nice to state under `Prerequisites` that it is a prerequisite to have the moodle code and where you can get it from, like it is done for docker.

**Comment by juanda99** [comment]
I think it would be better not to have the prerequisite. A good option could be to modify the base dockerfile and add an entrypoint. The entrypoint could be a bash script where moodle code could get loaded in case it's not present. 
It's similar as some official docker images, as wordpress.
Based on your code, I've done something like that.
You can see my Docker file and my entrypoint:
https://github.com/juanda99/moodle-docker-production/blob/master/moodle-3.8-apache/Dockerfile
https://github.com/juanda99/moodle-docker-production/blob/master/moodle-3.8-apache/docker-entrypoint.sh

**Comment by andrewnicols** [comment]
Sorry folks but this is _not_ intended as a production-ready tool. As the readme states:

> This repository contains Docker configuration aimed at Moodle developers and testers to easily deploy a testing environment for Moodle.

Please do not use this tool for your production image needs as it is not suitable for it.

Addign a docker-entrypoint is on my todo list for the php image but the whole image needs a restructure first.

In my opinion it does not make sense to add having a checkout of the codebase as a pre-requisite as this is a pre-requisite to development of Moodle itself. This is also stated as as a requirement in the Quick start.
