### ISSUE TITLE
Rename MOODLE_APP_VERSION env variable

### ISSUE THREAD

**Issue by NoelDeMartin** [moodlehq/moodle-docker#127]
As I mentioned in #126, it'd be better to rename this variable to follow the convention of prefixing them with `MOODLE_DOCKER_`.

However, this is a breaking change for some environments and it should be taken with care. Would it be a good idea to version the repo for this kind of things? That way we'd know when it's ok to make breaking changes or not.

Another option is to support both variables but only document the latter.

**Comment by stronk7** [comment]
I recently faced a similar thing in another issue and it shouldn't be hard to keep BC with the previous var name. Although finally I closed that PR... the idea was pretty much:

https://github.com/moodlehq/moodle-ci-runner/pull/26/files#diff-f94d47731dc2a21065e140897c19bf08R75-R77

Just in case it helps...

**Comment by NoelDeMartin** [comment]
Solved in #132
