### ISSUE TITLE
Cron setup missing

### ISSUE THREAD

**Issue by AdrianSanchezLopez** [moodlehq/moodle-docker#129]
Hi there, I have been testing and using these moodle docker images for a moodle setup with docker compose, but I am struggling with the cron job for the  'admin/cli/cron.php' script that moodle recomends.
Do you have something in the image 'moodlehq/moodle-php-apache' preventing the correct work of a cron moodle job? because following [the steps](https://docs.moodle.org/all/es/Cron) there is no way to make it work through Dockerfile commands.
Maybe you can set an example? Thanks

**Comment by stronk7** [comment]
Hi @AdrianSanchezLopez,

From `moodle-docker` (this product), that I can imagine, all you can do is to create a new container, with `cron` installed, in charge of invoking the needed calls to the `moodle-php-apache` one (maybe via web can be ok in this case, if you enable it.

Another option is to do it from the host, use its own cron system and then invoke, via `docker exec ...` the cron script in the  `moodle-php-apache`.

And finally, it's also possible to make (a child of) `moodle-php-apache` itself to be able to run cron. For doing that you will have to create your very own image, extending from it, and then installing `cron` (and maybe `sudo`), adding your schedule to cron, and make cron.php to run from there.

I did something similar recently for another image, not with apache but with a java server and it was not complex. You just need to run both cron daemon and then httpd.

If you can run Moodle's cron.php via `docker exec ...` then you should be able to call it with any of the 3 methods commented above. Just search for `apache php cron docker` and you should find some good examples.

In any case, I don't think this issue belongs here, so I'm closing it now. Feel free to research about it and come with anything to the https://github.com/moodlehq/moodle-php-apache if you find any problem or want to share your experience. Note that I've not checked if there is any problem, but I'm unable to imagine any, if you cannot get it running using `docker exec... ` feel free to create an issue in that repo with as many details as possible.

Ciao :-)

**Comment by geoffreyvanwyk** [comment]
In Ubuntu on WSL2, I added the cron with command `crontab -e`, then added this line:

```
* * * * * docker exec moodle-webserver-1 php /var/www/html/admin/cli/cron.php > /dev/null
```

Notice I left out `-it` after `exec` that one would normally have.
