### ISSUE TITLE
Xdebug 3.0.1 now fetched

### ISSUE THREAD

**Issue by djhipps** [moodlehq/moodle-docker#146]
The version of Xdebug now fetched from this Docker build will be 3.0.1. 
Could you please update the README to reflect something like the new config settings that will be required? 
There are mine for VSCODE on WSL2. As you can see they have dramatically changed and v2 settings will not work. (I am happy to do this if you want).

https://xdebug.org/updates
https://xdebug.org/docs/upgrade_guide

> ; Settings for Xdebug Docker configuration
> xdebug.mode=debug
> xdebug.start_with_request=yes
> xdebug.client_port=9003
> xdebug.remote_handler=dbgp
> xdebug.idekey=VSCODE
> xdebug.discover_client_host=false
> xdebug.client_host=host.docker.internal
> xdebug.log=/var/log/xdebug.log
> 
> {
>     "version": "0.2.0",
>     "configurations": [
> 
>         {
>             "name": "Listen for XDebug WSL",
>             "type": "php",
>             "request": "launch",
>             "port": 9003,
>             "log": true,
>             "externalConsole": false,
>             "pathMappings": {
>                 "/var/www/html": "${workspaceRoot}",
>             },
>             "hostname": "localhost"
>         },
>     ]
> }
> 
>

**Comment by mattrice** [comment]
I can confirm this config works for XDebug 3.0.3 and VSCode 1.54.3

**Comment by stronk7** [comment]
Hi @djhipps ,

this is being handled by #163, please take a look there in case there is anything  worth considering to be added there.

I'm closing this now, thanks!

**Comment by adpe** [comment]
Thanks @djhipps 

Actually my PR will not set custom IDE configuration options, just the two needed options are set. Can you please try it out and check if it will work with VSCode? For my case I can confirm, that for PHPStorm no other configuration options must be set.

Greets
Adrian
