### ISSUE TITLE
Failed to program FILTER chain

### ISSUE THREAD

**Issue by davejal** [moodlehq/moodle-docker#157]
Hi,

I'm getting the following error, anyone know how to fix this?

> [root@centos81 moodle-docker]# bin/moodle-docker-compose up -d
> Creating network "moodle-docker_default" with the default driver
> ERROR: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-9f4dfff0d6a0 -j DOCKER: iptables v1.8.4 (nf_tables): Chain 'DOCKER' does not exist
> Try `iptables -h' or 'iptables --help' for more information.
>  (exit status 2)

**Comment by scara** [comment]
Hi @davejal,
your issue is related to your environment and not to this project.

I'm guessing you "forced" the installation of docker in CentOS 8: have you already tried a reboot or better a `sudo systemctl restart docker`?

HTH,
Matteo

**Comment by stronk7** [comment]
Thanks @scara ! I think you're correct and that's local problem, so I'm going to close this now.
