### ISSUE TITLE
Deprecated MOODLE_APP_VERSION variable not properly handled on Windows

### ISSUE THREAD

**Issue by NeillM** [moodlehq/moodle-docker#166]
If you use the MOODLE_APP_VERSION on windows the MOODLE_DOCKER_APP_VERSION variable is set with speech marks around it. i.e. as **"latest"**, rather than **latest** causing moodle-docker not to start with a message like:

ERROR: no such image: moodlehq/moodleapp:"latest": invalid reference format

**Comment by NeillM** [comment]
I have submitted a pull request to fix this.

**Comment by stronk7** [comment]
Related to this, I've created #168 to see if we can have Windows scripts covered in some way.

**Comment by stronk7** [comment]
Closing, now that #167 has been merged, thanks!
