### ISSUE TITLE
Remove sticky selenium/chrome once it's solved upstream

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-docker#177]
selenium/standalone-chrome:3.141.59-2021729 introduced some regression causing the webdriver not to connect as expected. So, we did #176 to switch to known-to-work version.

Some related links:

- https://github.com/moodlehq/moodle-plugin-ci/issues/121
- https://github.com/testcontainers/testcontainers-java/pull/4315
- https://github.com/SeleniumHQ/docker-selenium/issues/1351
- Underlying Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1228625

This issue is about to remove the sticky version once the problem is solved upstream or we find an alternative solution (disable-gpu seems to work too, for example).

**Comment by stronk7** [comment]
Side note: we'll have to also do https://github.com/moodlehq/moodle-plugin-ci/issues/123 is a similar way.

**Comment by stronk7** [comment]
Was looking for other selenium stuff when I saw that they have already added a fix for the latest selenium images not starting properly: https://github.com/SeleniumHQ/docker-selenium/blob/selenium-3/NodeChrome/wrap_chrome_binary
 (add —disable-gpu)

So maybe we can give it a try and proceed with the unpin.

**Comment by dahrens** [comment]
I've tested locally right now and it looks like you can revert the commit that pinned to the specific version.
