### ISSUE TITLE
Set chrome as browser fpr BEHAT-tests but firefox is still used

### ISSUE THREAD

**Issue by Dmfama20** [moodlehq/moodle-docker#180]
Hello everybody,
I set up chrome for BEHAT tests:
`export MOODLE_DOCKER_BROWSER=chrome`
But when I run the BEHAT tests firefox is still used

```
bin/moodle-docker-compose exec -u www-data webserver php admin/tool/behat/cli/run.php --tags=@mod_qcreate
Running single behat site:
Moodle 3.11.2 (Build: 20210729), 0a21811ed09899ed27a99276cd0d744961d2b449
Php: 7.3.29, mariadb: 10.5.11, OS: Linux 5.11.0-25-generic x86_64
Run optional tests:
- Accessibility: No
Server OS "Linux", Browser: "firefox"
Started at 06-08-2021, 21:17
```

Any Idea whats going wrong here?
Some details:
Im running Moodle 3.11 and Ubuntu 20.04.

Best,
Alex

**Comment by scara** [comment]
Hi @Dmfama20,
I guess you hit a bug; can you give the patch below a try?

``` diff
index 2ede0f9..bbeed76 100644
--- a/base.yml
+++ b/base.yml
@@ -12,7 +12,7 @@ services:
       MOODLE_DOCKER_DBNAME: moodle
       MOODLE_DOCKER_DBUSER: moodle
       MOODLE_DOCKER_DBPASS: "m@0dl3ing"
-      MOODLE_DOCKER_BROWSER: firefox
+      MOODLE_DOCKER_BROWSER: ${MOODLE_DOCKER_BROWSER}
       MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
   db:
     image: postgres:11

```
HTH,
Matteo

**Comment by scara** [comment]
Hi @Dmfama20,
I give the current upstream code a try and it work w/o any patch:
```
Running single behat site:
Moodle 4.0dev (Build: 20210805), 0d0e66d37c6271657d76f948db9eeb10c139e7ae
Php: 7.4.21, mysqli: 5.7.34, OS: Linux 3.10.0-1160.36.2.el7.x86_64 x86_64
Run optional tests:
- Accessibility: No
Server OS "Linux", Browser: "chrome"
Started at 08-08-2021, 04:09


No scenarios
No steps
0m1.36s (44.62Mb)
```
because of the compose will include even the file `selenium.chrome.yml` which actually change the env var above, "improved" w/ my patch.

You may share here:
1. the commit id of your `moodle-docker` code
1. your exact sequence of export and CLI commands

and I'll try to replicate it on my side.

HTH,
Matteo

**Comment by Dmfama20** [comment]
Hi @scara ,
I added the line of your first post and now chrome is running as expected. I had to Shut down and destroy containers one time to make the changes work.

Best,
Alex

**Comment by dahrens** [comment]
> I added the line of your first post and now chrome is running as expected. I had to Shut down and destroy containers one time to make the changes work.

It should be sufficient to just destroy and recreate without this patch. Based on `MOODLE_DOCKER_BROWSER` the [startup script](https://github.com/moodlehq/moodle-docker/blob/master/bin/moodle-docker-compose#L69) replaces the selenium container image and the environment variable by loading [this YAML](https://github.com/moodlehq/moodle-docker/blob/master/selenium.chrome.yml) on top of `base.yaml`.

The proposed patch removes the default value and enforces the user to define a value to be able to run the behat tests with firefox. Utilized [here](https://github.com/moodlehq/moodle-docker/blob/master/config.docker-template.php#L56).

I'd suggest to enhance the README to make this more clear.

**Comment by stronk7** [comment]
Closing this, because of #181, just merged, addressing the README, making it clearer.
