### ISSUE TITLE
How to change only localhost binding?

### ISSUE THREAD

**Issue by fishfree** [moodlehq/moodle-docker#186]
I followed the REAME, but `docker ps` always shows `127.0.0.1:8000->80/tcp`
I tried editing from `MOODLE_DOCKER_WEB_HOST` from `localhost` to` 0.0.0.0` in both ` bin/moodle-docker-compose.cmd `and `bin/moodle-docker-compose` files, but still no work.

**Comment by scara** [comment]
Hi @fishfree,
what is your final goal?

In my DEV environment the Docker Host runs on a different server and I'm used to set `MOODLE_DOCKER_WEB_HOST` with the proper IP address of my Docker Host i.e. an explicit IP address binding - see e.g. the _Testing Instruction_ of [MDL-63770](https://tracker.moodle.org/browse/MDL-63770).

HTH,
Matteo

**Comment by fishfree** [comment]
@scara Thank you for your help. In fact, I tried run `export MOODLE_DOCKER_WEB_HOST=139.***.***.***` (my public IP) before running `bin/moodle-docker-compose up -d`, but  `docker ps` always shows `127.0.0.1:8000->80/tcp`
