### ISSUE TITLE
Where are error logs outputs?

### ISSUE THREAD

**Issue by srssaulo** [moodlehq/moodle-docker#205]
webserver does not  output errors to apache_log_dir

**Comment by scara** [comment]
Hi @srssaulo,
the PHP on Apache is provided by https://github.com/moodlehq/moodle-php-apache which in turns comes from https://github.com/docker-library/php: read more [here](https://github.com/docker-library/php/blob/c1d608310dcc10f419f2b344f57609162797f1eb/8.1/bullseye/apache/Dockerfile#L84-L88).

HTH,
Matteo

**Comment by mattporritt** [comment]
To help people in the future to do less digging:
By default Apache is set to output logs to stdout. This means you can view them in the container logs.

So for example if your webserver container was called `moodlemaster-webserver-1` running this command from a terminal on the docker host machine will show you the logs:
`docker logs -f moodlemaster-webserver-1`

**Comment by stronk7** [comment]
Thanks, @scara & @mattporritt !
