### ISSUE TITLE
Update git clone command

### ISSUE THREAD

**Issue by alfonso-salces** [moodlehq/moodle-docker#208]
Trying to follow the readme documentation I found an Issue related with **git clone request protocol**.

**Outdated points:**
https://github.com/moodlehq/moodle-docker#use-containers-for-running-behat-tests-for-the-moodle-app
https://github.com/moodlehq/moodle-docker/blob/master/tests/app-setup.sh

Command executed:
`git clone git://<repo>`

Throwed error:
Clonando en 'moodle-local_moodlemobileapp'...
fatal: error remoto:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

I will create a Pull Request to fix that, using git clone with **https** protocol.

**Comment by alfonso-salces** [comment]
Pull request with mentioned fix: https://github.com/moodlehq/moodle-docker/pull/209

**Comment by stronk7** [comment]
Closing this because it was fixed indirectly by #210 . Thanks for the issue and the PR!

**Comment by scara** [comment]
Hi @stronk7,
> Closing this because it was fixed indirectly by #210 .

for the sake of community refs 😉, it was fixed by #211.

HTH,
Matteo

**Comment by stronk7** [comment]
Ah, fun. I copied the reference from #209, where I also pointed, incorrectly, to #210.

You are right, #211 was the one fixing this, thanks!
