### ISSUE TITLE
master branch failing against moodle master - oracle

### ISSUE THREAD

**Issue by aspark21** [moodlehq/moodle-docker#219]
Currently only happens with [Behat (master, 8.0, oracle, chrome, behat)](https://github.com/aspark21/moodle-docker/runs/7483804352?check_suite_focus=true#logs)

https://github.com/aspark21/moodle-docker/runs/7483804352?check_suite_focus=true#step:4:2135
== Environment ==
!! database oracle (Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production) !!
[System] version 19 is required and you are running 11.2.0.2.0 - 
Error: Process completed with exit code 1.

Noticed this after rebasing a branch on this repo's master branch with a change that would have no impact on any of the tests.

**Comment by stronk7** [comment]
Wow, my fault. I was 99% I had already done this! In fact I ticked it in the TODO list of [MDL-71747](https://tracker.moodle.org/browse/MDL-71747) some weeks ago.

Sure i tested it against incorrect branch, grrr. Will look to #220  soon, thanks!
