### ISSUE TITLE
Document Docker CLI version requirements

### ISSUE THREAD

**Issue by NoelDeMartin** [moodlehq/moodle-docker#243]
With a recent update, I noticed that the `version: "2"` declaration in compose-files does not support the use of [Parameter Expansion](https://docs.docker.com/compose/env-file/#parameter-expansion). With `version: "3"` this works, but under further inspection I noticed this was working in the CI tests because they use the [compose plugin](https://docs.docker.com/compose/install/linux/) and I was using an old version of the `docker-compose` command (which is [used as a fallback](https://github.com/moodlehq/moodle-docker/blob/master/bin/moodle-docker-compose#L29)).

So I guess we should either update to `version: "3"` or document the minimum required version of the CLI.

See https://github.com/moodlehq/moodle-docker/pull/198#issuecomment-1340842093 for more details on this.

**Comment by paulholden** [comment]
Because I recall having this exact conversation with @stronk7 some time ago, just adding for reference (agree it should be documented):

Old version - doesn't work:

```
$ docker --version
Docker version 18.09.7, build 2d0083d
$ docker-compose --version
docker-compose version 1.8.0, build unknown
$ bin/moodle-docker-compose up -d
Compose v2 is not available in Docker CLI, falling back to use docker-compose script
ERROR: Invalid interpolation format for "image" option in service "selenium": "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX:-}:${MOODLE_DOCKER_BROWSER_TAG}"
```

Upgraded - works:

```
$ docker --version
Docker version 20.10.7, build f0df350
$ docker compose version
Docker Compose version v2.12.2
```

**Comment by scara** [comment]
Hi @paulholden,
```
$ docker-compose --version
docker-compose version 1.8.0, build unknown
```
vs
```
$ docker compose version
Docker Compose version v2.12.2
```
Guessing that https://github.com/docker/compose/releases/tag/v2.7.0 could be the minimum requirement.
Reading https://docs.docker.com/compose/release-notes/#290 I guess that we should suggest `2.10+`.

Could you give it a try, maybe `2.10.0` first and then `2.6.1`, the version before `2.7.0`?

No info found from the Release Notes for those still on the Compose `v1` path.

TIA,
Matteo

**Comment by stronk7** [comment]
Just trying to define this... some updates:

- Note that we have ditched those versions completely from all Yaml files (#283).
- That implies that we are required to use a docker-engine version compatible with the "[Compose Specification](https://docs.docker.com/compose/compose-file/)".
- Hence Docker Compose V2 is required. And that [seems to imply](https://docs.docker.com/compose/compose-file/) versions >= 1.27.0 (see [release notes](https://github.com/docker/compose/releases/tag/1.27.0)). September 2020!
- And that [seems to point](https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix) to Docker Engine v19.03.0 (although I've not seen anything in the [release notes](https://docs.docker.com/engine/release-notes/19.03/).
- Looking to those release notes, the first time that the "docker compose" is mentioned, is with Docker Engine v20.10.15 , May 2022 ([link](https://docs.docker.com/engine/release-notes/20.10/#201015)), and it shows explicitly that it comes with Docker compose v2.5.0 (really newer than the v1.27.0 requirement above.

So, unless we find other couples of docker-engine (>= v19.03.0) and docker-compose (>= 1.27.0) documented... I'd propose to declare:
- docker-engine requirement: v20.10.15
- docker-compose requirement: v2.5.0

And done, they are near 2y old versions and should work. If anybody detects any new requirement not available in those versions, we always can raise them. In any case, I'd add to the information above that it's always recommended to try to run the latest versions (bug fixes and friends).

Not sure how that looks to you, thoughts? Maybe I'm missing something, surely I am, heh.

Ciao :-)

**Comment by stronk7** [comment]
Note that there is #284 about to write down the above to docs.

We'll wait a few days to hear any objection. If nothing happens, I think that we can assume the PR as a good start point for the very-basic-requirements to be written down.

Ciao :-)
