### ISSUE TITLE
Invalid interpolation format 

### ISSUE THREAD

**Issue by aspark21** [moodlehq/moodle-docker#247]
'Invalid interpolation format for "image" option in service "selenium": "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX:-}:${MOODLE_DOCKER_BROWSER_TAG}"'

I'm assuming it's related to this change - https://github.com/moodlehq/moodle-docker/commit/07bb7cc4e5ac9ea9cf796aa59d3c7d8c860b6d6b

but then removing it on that option, just made a similar situation on the database version parameter pop up.

We were getting this under rhel7 on-prem but now we've moved our runners to use AWS spot instances running amazon linux and it seems fine on that.
So this might be an issue others encounter, so logging this for reference but I didn't find the actual root cause

(have just gone back to moodle-docker upstream latest now that mysql 8 available, rather than my basic fork)

**Comment by paulholden** [comment]
Hi @aspark21 - see the discussion in https://github.com/moodlehq/moodle-docker/issues/243 (you need to update your Docker install)

**Comment by aspark21** [comment]
ahah! Yes, sounds about right, Docker was kept updated on those VMs but Docker Compose less so
