### ISSUE TITLE
Unpin mariadb from 10.2.6

### ISSUE THREAD

**Issue by danpoltawski** [moodlehq/moodle-docker#25]
As discovered in Andrew's pull requests:
https://travis-ci.org/danpoltawski/docker-moodle/jobs/253151437

**Comment by danpoltawski** [comment]
We can just pin a version here, but perhaps an upstream bug?

**Comment by danpoltawski** [comment]
Confirming that this works ok on 10.2.6:
```
Running: bin/moodle-docker-compose exec -T webserver vendor/bin/phpunit core_dml_testcase lib/dml/tests/dml_test.php
Moodle 3.4dev (Build: 20170707), fdd9e4187a8f5e6ffe44eef11472de81c756ecef
Php: 7.1.6, mariadb: 10.2.6, OS: Linux 4.9.31-moby x86_64
PHPUnit 5.5.7 by Sebastian Bergmann and contributors.

...............................................................  63 / 103 ( 61%)
........................................                        103 / 103 (100%)

Time: 51.5 seconds, Memory: 36.00MB

OK (103 tests, 1178 assertions)
```

**Comment by danpoltawski** [comment]
Created https://tracker.moodle.org/browse/MDL-59583

**Comment by danpoltawski** [comment]
I have added a commit to pin the version for now. Lets use this issue to unpin it when the Moodle issue is resolved.

**Comment by scara** [comment]
Bumping.
@andrewnicols @stronk7: we can unpin it since [MDL-59098](https://tracker.moodle.org/browse/MDL-59098) should be near to be closed.
I'd create a PR about this unpinning and another, related but not to this issue, to move to MySQL 8, if you'll agree.

TIA,
Matteo

**Comment by stronk7** [comment]
Unpinned! Thanks!

Closing this :-)

**Comment by stronk7** [comment]
Uhm... maybe I did it too early... I'm facing problems with 10, now pointing to 10.3.x... will verify soon...
