### ISSUE TITLE
Mailpit UI no longer accessible

### ISSUE THREAD

**Issue by paulholden** [moodlehq/moodle-docker#272]
We should be able to access at http://localhost:8000/_/mail/

Using the `axllent/mailpit:v1.8` image allows that, but `latest` doesn't work correctly because it requires `MP_WEBROOT` environment variable be specified (see https://mailpit.axllent.org/docs/configuration/runtime-options/)

Trying to access that URL currently returns a blank page, and looking at the container error logs we see the following:

```
172.27.0.1 - - [13/Nov/2023:12:02:51 +0000] "GET /_/mail/ HTTP/1.1" 200 856 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
172.27.0.1 - - [13/Nov/2023:12:02:51 +0000] "GET /dist/app.js?v1.10.0 HTTP/1.1" 404 489 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
172.27.0.1 - - [13/Nov/2023:12:02:51 +0000] "GET /dist/app.css?v1.10.0 HTTP/1.1" 404 490 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0"
```

**Comment by stronk7** [comment]
It's curious that change of behaviour, because the variable already existed in older versions and we haven't needed to set it.

In any case, if it works with the proposed patch @ #273, I'm happy (and don't have much time to look in the history). So, see you there.

Thanks!
