### ISSUE TITLE
Quicker quick start

### ISSUE THREAD

**Issue by fulldecent** [moodlehq/moodle-docker#304]
I believe that every Moodle plugin project should include instructions to test their module in a live, local Moodle environment.

I also think that moodle-docker is the canonical Docker repo to use for developing and testing Moodle plugins.

This means that all the instructions at https://github.com/moodlehq/moodle-docker?tab=readme-ov-file#quick-start are incorporated into the development of every plugin.

That's a lot of instructions!

---

I hope that the setup for moodle-docker can be simplified greatly. Ultimately this can be whittled down to the single command:

```sh
cd $SOME_DIR
docker-compose up
```

This will load check out Moodle, create directories as needed, and run everything.

If additional configuration is required, like MOODLE_DOCKER_WWWROOT MOODLE_DOCKER_DB or whatever is in the shell script, those can be handled as additional options.

**Comment by serafdev** [comment]
I would like even quicker, just a `docker compose up -d` without even doing `cd`

**Comment by fulldecent** [comment]
That's good!

---

Here is my current progress here:

https://github.com/fulldecent/moodle-local_plugin_template/blob/00766d33b6ac9d1c80612b0475ecff983032d692/README.md#quick-start-playground

I think this is the current best practice for testing a plugin and these instructions should be included in the README of every plugin's repo.

**Comment by paulholden** [comment]
See https://github.com/moodlehq/moodle-docker/pull/249 for .env support (which would be the "Quicker quick start") - the rest of this request appears to be asking for support for your own plugin, so I'll close this one
