### ISSUE TITLE
Moodle mapping to localhost not always fine

### ISSUE THREAD

**Issue by scara** [moodlehq/moodle-docker#33]
If you run the container host engine on a machine different from your local dev environment, Moodle [mapping to `localhost`](https://github.com/danpoltawski/moodle-docker/blob/246e98a1b2cf83723304d42241b16e3bd4ff9440/config.docker-template.php#L16) is fine for automated tests "only".

I know that you don't like too many env variables :wink: but what about using `$_SERVER` (e.g. `SERVER_NAME` or `HTTP_HOST` or `SERVER_ADDR`) or kind-of-`gethostname()` - via script, to get the name of the host and not the one of the container, unroutable - here being the scope of this composition mainly for dev/test purposes i.e. no need to preserve the uniqueness of URLs eventually stored in different "sessions"?
I'd be happy to contribute here according to your thoughts.

Pinging @andrewnicols too, since his [proxy solution](https://github.com/danpoltawski/moodle-docker/blob/894365bb597f9ab6976f64d7d2f4a2fdd7ba9b2d/assets/web/apache2_mailhog.conf) for some ancillary services has unlocked the access of those services from `localhost` only.

TIA,
Matteo

**Comment by danpoltawski** [comment]
I actually think this is decent case for an ENV variable (defaulting to localhost)

**Comment by scara** [comment]
TNX, will do 😉 !
