### ISSUE TITLE
Moodle refuses to setup on the Oracle image

### ISSUE THREAD

**Issue by NeillM** [moodlehq/moodle-docker#34]
When using the Oracle image and I try to initialise either behat or phpunit

I get the following error:

'The site administrator should verify server configuration</p><p>Oracle PL/SQL Moodle support package MOODLELIB is not installed! Database administrator has to execute /lib/dml/oci_native_moodle_package.sql script.'

The database logs from the docker instance:

`db_1         | Starting Oracle Net Listener.`
`db_1         | Starting Oracle Database 11g Express Edition instance.`
`db_1         | ERROR:`
`db_1         | ORA-28002: the password will expire within 7 days`
`db_1         | System altered.`
`db_1         | /usr/sbin/startup.sh: running /docker-entrypoint-initdb.d/01-moodle-package.sql`
`db_1         | SQL*Plus: Release 11.2.0.2.0 Production on Thu Aug 17 10:43:56 2017`
`db_1         | Copyright (c) 1982, 2011, Oracle.  All rights reserved.`
`db_1         | ERROR:`
`db_1         | ORA-28002: the password will expire within 7 days`
`db_1         | Connected to:`
`db_1         | Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production`
`db_1         | Connected.`
`db_1         | Package created.`
`db_1         | Package body created.`
`db_1         | No errors.`
`db_1         | Package body created.`
`db_1         | SQL> Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production`
`db_1         | /usr/sbin/startup.sh: running /docker-entrypoint-initdb.d/02-moodle-user.sql`
`db_1         | SQL*Plus: Release 11.2.0.2.0 Production on Thu Aug 17 10:43:57 2017`
`db_1         | Copyright (c) 1982, 2011, Oracle.  All rights reserved.`
`db_1         | ERROR:`
`db_1         | ORA-28002: the password will expire within 7 days`
`db_1         | Connected to:`
`db_1         | Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production`
`db_1         | Connected.`
`db_1         | Profile altered.`
`db_1         | User created.`
`db_1         | Grant succeeded.`
`db_1         | Grant succeeded.`
`db_1         | Grant succeeded.`
`db_1         | Grant succeeded.`
`db_1         | Grant succeeded.`
`db_1         | System altered.`
`db_1         | Database altered.`
`db_1         | Database closed.`
`db_1         | Database dismounted.`
`db_1         | ORACLE instance shut down.`
`db_1         | ORACLE instance started.`
`db_1         | Total System Global Area  601272320 bytes`
`db_1         | Fixed Size                   2228848 bytes`
`db_1         | Variable Size              180358544 bytes`
`db_1         | Database Buffers   415236096 bytes`
`db_1         | Redo Buffers                 3448832 bytes`
`db_1         | Database mounted.`
`db_1         | Database opened.`
`db_1         | SQL> Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production`

I an running it on Windows 7 via the Docker Toolbox

Docker version 17.06.0-ce, build 02c1d87

**Comment by NeillM** [comment]
The environment variables set on the 'moodledocker_db_1' container when the Oracle image is used are:

- POSTGRES_PASSWORD
- POSTGRES_USER
- POSTGRES_DB
- PATH
- ORACLE_ALLOW_REMOTE

**Comment by scara** [comment]
For the sake of clarity: `ORACLE_ALLOW_REMOTE` comes from a not-working suggestion described in https://moodle.org/mod/forum/discuss.php?d=351402#p1439947.

**Comment by NeillM** [comment]
It seems to be present if I have that setting in the file or not

**Comment by NeillM** [comment]
Playing directly with the moodle-db-oracle package it looks as though the POSTGRES settings are ignored.

When I login to that using the Oracle SQL developer console I can see no Packages in the Moodle users 'Package' area, however I can see the MOODLELIB package if I go to:

Other users -> SYS -> Packages

I wonder if the moodle user is just not being given enough capabilities on it?

**Comment by scara** [comment]
Hi @NeillM,
here is my successful try running on CentOS 7 and using the latest `master` branch (moodle/moodle@27466d7548de99cbb050027acc3e809ce49ad2e9):
```
# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false
# docker-compose version
docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
# export MOODLE_DOCKER_DB=oracle
# cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php
# bin/moodle-docker-compose up -d
...
Creating moodledocker_selenium_1
Creating moodledocker_db_1
Creating moodledocker_mailhog_1
Creating moodledocker_webserver_1
# docker ps --format "{{.Names}}"
moodledocker_webserver_1
moodledocker_db_1
moodledocker_mailhog_1
moodledocker_selenium_1
# bin/moodle-docker-compose exec webserver php admin/tool/phpunit/cli/init.php
Initialising Moodle PHPUnit test environment...
...
++ Success ++

PHPUnit test environment setup complete.
# bin/moodle-docker-compose exec webserver vendor/bin/phpunit enrol_meta_plugin_testcase enrol/meta/tests/plugin_test.php
Moodle 3.4dev (Build: 20170817), 27466d7548de99cbb050027acc3e809ce49ad2e9
Php: 7.1.7, oci: 11.2.0.2.0, OS: Linux 3.10.0-514.26.2.el7.x86_64 x86_64
PHPUnit 5.5.7 by Sebastian Bergmann and contributors.

........                                                            8 / 8 (100%)

Time: 1.21 minutes, Memory: 64.00MB

OK (8 tests, 266 assertions)
```
Looks like an issue with the Toolbox.

In the mean time, I'll give your PR a try (https://tracker.moodle.org/browse/MDL-43176?focusedCommentId=475746&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-475746).

HTH,
Matteo

**Comment by NeillM** [comment]
I tried it on a Surface Pro we have laying about (i.e. Windows 10 with Docker for Windows) and that had the same issue with initialising the Oracle database for me.

**Comment by scara** [comment]
Hi @NeillM,
yesterday night I prepared a Win10Pro VM running Docker for Windows and this morning I got a successful running on the latest master (download as zip in the Win10Pro VM, moodle/moodle@27466d7548de99cbb050027acc3e809ce49ad2e9):
```
>docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
>docker-compose version
docker-compose version 1.14.0, build c7bdf9e3
docker-py version: 2.3.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
>set MOODLE_DOCKER_WWWROOT=C:\Projects\Moodle\moodle-master

>set MOODLE_DOCKER_DB=oracle

>cd C:\Projects\Moodle\moodle-docker-master
>copy config.docker-template.php %MOODLE_DOCKER_WWWROOT%\config.php
        1 file(s) copied.
>bin\moodle-docker-compose.cmd up -d
Creating network "moodledockermaster_default" with the default driver
...
>docker ps --format "{{.Names}}"
moodledockermaster_webserver_1
moodledockermaster_selenium_1
moodledockermaster_db_1
moodledockermaster_mailhog_1

>bin\moodle-docker-compose.cmd exec webserver php admin/tool/phpunit/cli/init.php
Initialising Moodle PHPUnit test environment...
...

++ Success ++

PHPUnit test environment setup complete.
>bin\moodle-docker-compose.cmd exec webserver vendor/bin/phpunit enrol_meta_plugin_testcase enrol/meta/tests/plugin_test.php
Moodle 3.4dev (Build: 20170817)
Php: 7.1.7, oci: 11.2.0.2.0, OS: Linux 4.9.36-moby x86_64
PHPUnit 5.5.7 by Sebastian Bergmann and contributors.

........                                                            8 / 8 (100%)

Time: 8.01 minutes, Memory: 64.00MB

OK (8 tests, 266 assertions)
```
Could you share the first commands output about your `docker*` versions?

Note: running Oracle tests is slower than using OSS DBs, and running it on Hyper-V (maybe since nested on ESXi 6.0, but on SSD) is my slowest dev experience ever 😉 (monitored via `docker stats --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}\t{{.BlockIO}}"`.

TIA,
Matteo

**Comment by danpoltawski** [comment]
I don't think there is a problem with the moodle package/user setup (since your output looks ok), it sounds to me like its not conecting to the correct database

**Comment by NeillM** [comment]
I'll have another play with it at some point and see if I can figure anything more about what is going wrong.

If there are any suggestions I would be happy to try them.

**Comment by NeillM** [comment]
This is the result of $DB->export_dbconfig() after the exception has been triggered.

```php
object(stdClass)#8 (8) {
  ["dbtype"]=>string(3) "oci"
  ["dblibrary"]=>string(6) "native"
  ["dbhost"]=>string(2) "db"
  ["dbname"]=>string(2) "XE"
  ["dbuser"]=>string(6) "moodle"
  ["dbpass"]=>string(9) "m@0dl3ing"
  ["prefix"]=>string(2) "m_"
  ["dboptions"]=>array(2) {
    ["dbcollation"]=>bool(false)
    ["dbport"]=>int(1521)
  }
}
```

**Comment by NeillM** [comment]
If I start up a standalone instance of moodle-db-oracle the MOODLELIB package is on the SYS user.

After trying to connect via Moodle there was a faulty MOODLELIB package against the MOODLE user as well. It looks as though it was faulty because Oracle is rather sensitive to the line endings (i.e. the version of the file in my local repository has been converted to Windows style line endings on download)

After putting a UNIX encoded line endings version of /lib/dml/oci_native_moodle_package.sql Moodle would connect to the Oracle database.

Which means that I should now be able to run tests against Oracle.

It does make it look as though the MOODLELIB package that is added as part of the image setup script is not setup correctly for Moodle to use it though...

**Comment by scara** [comment]
Great investigative work!
Could you try to use the file from the zip archive and not extracting it from git?

I guess the issue could be in your local git config - guessing a default `$ git config --global core.autocrlf true` instead of `input` or `false` - rather than in that file.

TIA,
Matteo

**Comment by NeillM** [comment]
When I use the file direct from the archive (i.e. with Unix line endings) I am able to connect.

But that the /lib/dml/oci_native_moodle_package.sql file is being accessed does mean that Moodle is not able to use the MOODLELIB package that is created as part of the docker image setup.

**Comment by scara** [comment]
It depends on how you've configured your local git env, when you checked out your local branch (the one mapped into the Moodle docker env via `MOODLE_DOCKER_WWWROOT`).
What is the output of:
```
$ git config core.autocrlf
```
?
TIA,
Matteo

**Comment by NeillM** [comment]
My git client does do the auto changing of line endings.

**Comment by scara** [comment]
Guessing you can still configure it 😁: what client are you using?

**Comment by NeillM** [comment]
I have created: https://tracker.moodle.org/browse/MDL-60041 to make a change that will force /lib/dml/oci_native_moodle_package.sql to always have Unix line endings no matter the auto crlf settings.

**Comment by NeillM** [comment]
The query that tests if the package is installed is:

```sql
SELECT 1
FROM user_objects
WHERE object_type = 'PACKAGE BODY'
  AND object_name = 'MOODLELIB'
  AND status = 'VALID';
```

see: https://github.com/moodle/moodle/blob/master/lib/dml/oci_native_moodle_database.php#L1762

The user_objects table only contains references to things owned by the current user: https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_4378.htm#i1634422

The moodle-db-oracle image creates the MOODLELIB package on the sys user https://github.com/moodlehq/moodle-db-oracle/blob/master/root/docker-entrypoint-initdb.d/01-moodle-package.sql. This means that MOODLE cannot recognise that it exists even though the moodle user has the capability to execute it.

**Comment by NeillM** [comment]
I have created a pull request in moodle-db-oracle that makes create the MOODLELIB against the moodle user.

https://github.com/moodlehq/moodle-db-oracle/pull/1

**Comment by scara** [comment]
I guess that, on a product basis, you can't wire the name of the user into the script and never read in the Moodle Community about the need for it but:
```
SQL> GRANT EXECUTE ON moodlelib to moodle;
Grant succeeded.
SQL> GRANT EXECUTE ON DBMS_LOCK to moodle;
Grant succeeded.
```

**Comment by NeillM** [comment]
I'm going to close this since it isn't a bug with the docker images, and I have a Moodle tracker issue to look at the root cause.
