### ISSUE TITLE
This repository has been transfered to moodlehq organisation

### ISSUE THREAD

**Issue by danpoltawski** [moodlehq/moodle-docker#35]
It started in my personal account to 'germinate', but now is transfred to Moodle HQ organisation (particularly as I am leaving Moodle HQ in a few weeks). There will be a few loose ends to tie up here an in the associated docker images.

**Comment by danpoltawski** [comment]
One issue encountered immediately is #36

**Comment by danpoltawski** [comment]
#36 was not related to this move, thankfully.

I was thinking about giving some sort of grace period before deleting my docker hub images (so we only have the HQ ones to avoid confusion), but on further thought I think its better to remove them sooner than later.

**Comment by stronk7** [comment]
Thanks Dan!
