### ISSUE TITLE
Fixes for README.md

### ISSUE THREAD

**Issue by abias** [moodlehq/moodle-docker#42]
Hi Dan,

I just started working with this tool and have some fixes for README.md:
* On https://github.com/moodlehq/moodle-docker#advanced-usage, the link to "bin/moodle-docker-compose" is broken
* On https://github.com/moodlehq/moodle-docker#companion-docker-images, the link to moodle-php-apache should be labeled "moodle-php-apache" instead of "moodle-apache-php" 

Thanks,
Alex

**Comment by danpoltawski** [comment]
Ooops, thanks! Fix coming shortly, unless you want to do a pull request? :)

**Comment by abias** [comment]
Done. I lazily edited the files in Github directly.
