### ISSUE TITLE
Don't expose web port and vnc port to the world by default

### ISSUE THREAD

**Issue by abias** [moodlehq/moodle-docker#64]
I have seen that - at least on my Docker for Mac installation - the web port (default: 8000) and the vnc port (default: 5900) of a running Moodle docker instance is exposed to the world and can be reached from outside my computer.

While I can prevent unauthorized access to these ports with a firewall on my Mac and while I can see situations where accessing the Moodle docker instance from the outside can be useful, I think exposing the ports to the world is a exception for development and testing and thus should not be the default.

Is there a possibility to disable exposing the ports from within the moodle-docker configuration and, if yes, can we create a env variable to control exposing the ports, defaulting to no?

**Comment by danpoltawski** [comment]
I think that if you set the port config to ‘127.0.0.1:8000’ it should do this

**Comment by stronk7** [comment]
Closing as far #66 has been merged!
