### ISSUE TITLE
What is the psql port expose for db to connect from client ?

### ISSUE THREAD

**Issue by asnawisaharuddin** [moodlehq/moodle-docker#68]

**Comment by asnawisaharuddin** [comment]
i solve by adding this in docker-compose conf.

ports:
      - "5432:5432"

Is there env conf for the port?

**Comment by scara** [comment]
Hi @asnawisaharuddin,
yes you can do that way or, just add https://moodle.org/plugins/local_adminer to your dev code to access the database via a web interface.

There's no env configuration for those ports yet but you could even propose here a pull request e.g. providing a new `ports.debug.yml` w/ which optionally map all the services but please keep care of the following items, based on the past issues:
1. do not create a complex env configuration
1. people is asking for limiting the access of the current set of ports strictly to `127.0.0.1` for security purposes
1. this is a toolbox for automation testing purposes first and it can be successfully used for dev purposes too

HTH,
Matteo
