### ISSUE TITLE
Add support for Global Search

### ISSUE THREAD

**Issue by rlorenzo** [moodlehq/moodle-docker#69]
Correct me if I am wrong, but I do not see Global Search support in these docker containers. Would be nice to add them in the container builds.

**Comment by danpoltawski** [comment]
+1

**Comment by stronk7** [comment]
Sorry @rlorenzo , I'm a little bit confused. With MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES enabled... an instance of solr is launched (for later use by tests).

Isn't that enough? What else would you want, getting it configured for normal use, maybe? (I mean, no phpunit/behat tests)

Ciao :-)

**Comment by rlorenzo** [comment]
@rlorenzo  Maybe something got added since the 3 years this request was added. What configure do I add if I launch with the added services?

**Comment by stronk7** [comment]
For tests (phpunit and behat), all you need to do is to set:
```
export MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES=yes
```

and, automatically, a solr instance will be started and used by tests.

If you want to use that instance for normal use (apart from tests), its information is:

- hostname: solr
- port: 8983
- indexname: test

All you have to do is to setup the config values above via UI, or using CLI:
```
php admin/cli/cfg.php --component=search_solr --name=server_hostname --set=solr
php admin/cli/cfg.php --component=search_solr --name=server_port --set=8983
php admin/cli/cfg.php --component=search_solr --name=indexname --set=test
```

And then, the moodle instance will have solr at hand.

Ciao :-)
