### ISSUE TITLE
Can we set pathtogs in the config file?

### ISSUE THREAD

**Issue by kwiliarty** [moodlehq/moodle-docker#75]
Moodle's default `pathtogs` setting is `/usr/bin/gs` but the webserver container invoked by moodle-docker has gs at `/usr/local/bin/gs`. This means, for instance, that PDF annotation does not work until one updates the system paths. Is there some way that we can have the expected path on moodlehq/moodle-php-apache?

**Comment by kwiliarty** [comment]
Sorry, I'll close this here and open it on moodle-php-apache.

**Comment by kwiliarty** [comment]
https://github.com/moodlehq/moodle-php-apache/issues/20

**Comment by kwiliarty** [comment]
Or maybe an easy fix is to add it to the config file. I'm going to reopen this in case it seems better to solve it here after all. It would keep the php image lighter.

**Comment by kwiliarty** [comment]
Nevermind. I don't know why I was seeing a wrong path at all. Very odd. Sorry for the noise.

**Comment by andrewnicols** [comment]
Well that was a rollercoaster ;)

Confirmed that it's available in `/usr/bin/gs`

**Comment by kwiliarty** [comment]
Thanks for checking, and again apologies. I wish I knew how I got into that state, but I can't reproduce it, so clearly I just did something silly.
