### ISSUE TITLE
Add suport for .env files

### ISSUE THREAD

**Issue by jpahullo** [moodlehq/moodle-docker#80]
docker-compose suport `.env` files to load environment variables.

Since the `bin/moodle-docker-compose` script expects two environment variables already set up, it makes impossible to let docker-compose use the content of the `.env` for value replacing on the configuration loaded from YML files.

**Proposal:**

I think it is a very easy step to check if the file exists on the `/` directory, and load all configuration from the `.env` file before guard conditions start.

**Comment by scara** [comment]
Hi @jpahullo,
the idea to mimic https://docs.docker.com/compose/environment-variables/#the-env-file looks nice: 👍 .

You should run something like `env $(cat .env | grep -v ^#  | xargs)` when starting the shell script `bin/moodle-docker-compose`.
Something similar should be done for the Windows shell command too (`bin/moodle-docker-compose.cmd`).

Would you mind to contribute here with a pull request?

**Comment by jpahullo** [comment]
My idea is to do that for the linux script. I do not know anything about windows. Could you do that for the windows script?

Thanks for suggesting.

I made a trial and using a simple command like `. ${basedir}/.env` worked like a charm. It would be sufficient for you?

**Comment by jpahullo** [comment]
This is also really helpful since you do not need to `export` variables and have side effects when running several instances.

When using `export` variables from command line and using the same shell instance, I had some side effects. I had to remember what project name and other variables I was using to just replace their value to what I needed actually.

Using `.env` files in every `moodle-docker` directory, you can work smoothly with all your own instances without side effects, because there are no global variables set on the shell.

**Comment by scara** [comment]
Hi @jpahullo,
I agree w/ you, `export` is a bad beast in this case since it makes "global" something that should be local to the single execution.
We're running a bash script so using `.` (dot) should be fine since it's the same as `source` (not tested yet).

For the Windows counterpart probably CALLing the dotenv file should do the trick... need a bit of spare time to test it.

HTH,
Matteo

**Comment by skodak** [comment]
I have proposed support **./moodle-docker.env** in https://github.com/moodlehq/moodle-docker/pull/232

**Comment by jpahullo** [comment]
Closing in favour of #232
