### ISSUE TITLE
 Folder Duplication in URL path (/moodle/moodle/...)

### ISSUE THREAD

**Issue by Isadoramenezes** [moodlehq/moodle-docker#87]
Dear community,

We are running Moodle at micro-service architecture (Docker), in such a way that we have application in one container and database in another. They communicate with each other, and we can navigate normally through the application, without any kind of trouble. However, when we try to modify Moodle resources, like creating a course, new user, editing its content and so on, it is duplicating the folder "/moodle/" in the URL path, which is causing 404 Error (Not Found).

For instance, if we try to create a new user, the application tries to find "/moodle/moodle/login/signup.php". See that it is duplicating folder moodle in this path. How can I workaround this problem?

**Comment by scara** [comment]
HI @Isadoramenezes,
are you using the containers from Moodle HQ - which mainly target a dev/test env - or your own ones?
In the letter case, you should post your question, with more details about the stack "coded" in each container, in https://moodle.org/mod/forum/view.php?id=50 to get (free) support about your issue.

HTH,
Matteo
