### ISSUE TITLE
Moodle 3.2.9 on Docker

### ISSUE THREAD

**Issue by nix0x00** [moodlehq/moodle-docker#88]
Hi,

Can someone provide me a good documentation for the installation of Moodle on docker, as the README file's documentation is not clear for someone who is new to Docker. I am trying to install only moodle version 3.2.9 with no maillog etc features.
Also I want to use external DBMS (outside container of the server itself) with reverse nginx proxy.
Because I am facing some broken css/js/php files error with local installation on the server (Centos 7). 
Already posted the issue days ago but still no reply on Moodle forum.

https://moodle.org/mod/forum/discuss.php?d=374426

https://serverfault.com/questions/925791/moodle-error-during-installation

**Comment by scara** [comment]
Hi @nix0x00,
I'll reply in the Community: running a Reverse Proxy in front of Moodle requires a config setting, regardless being Moodle deployed via container.

HTH,
Matteo
