### ISSUE TITLE
Problem setting moodle locally

### ISSUE THREAD

**Issue by prondubuisi** [moodlehq/moodle-docker#97]
I have sucessfully run the docker commands here 
![module installation](https://user-images.githubusercontent.com/22311928/53539130-a8432900-3b10-11e9-938d-5802c8397491.png)
but when I navigate to my browser I get an error
![browser](https://user-images.githubusercontent.com/22311928/53539205-ef311e80-3b10-11e9-8e06-5dea9715b8d6.png)
Besides after the docker files is done installing I see no additional files, So am wondering if this docker installation is to completely install the Moodle developer environment or just for Tests

**Comment by andrewnicols** [comment]
Hi @prondubuisi ,

Please see the README. The MOODLE_DOCKER-WWWROOT should be the location of your Moodle checkout, not the location of this tool.

You will not see any additional files in your repo.
