### ISSUE TITLE
PHP 7.1 mcrypt is missing

### ISSUE THREAD

**Issue by vsotirasqmplus** [moodlehq/moodle-docker#99]
inside the PHP 7.1 I cannot see the mcrypt module being included , so we could start the transformation to the new library

**Comment by vsotirasqmplus** [comment]
Attempted to install it and failed

root@9dd2d41d44be:/var/www/html# pecl install channel://pecl.php.net/mcrypt-1.0.2
pecl/mcrypt requires PHP (version >= 7.2.0, version <= 7.4.0, excluded versions: 7.4.0), installed version is 7.1.26
No valid packages found
install failed
root@9dd2d41d44be:/var/www/html# php -v
PHP 7.1.26 (cli) (built: Jan 11 2019 02:44:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.26, Copyright (c) 1999-2018, by Zend Technologies

**Comment by vsotirasqmplus** [comment]
Solution:
pecl install mcrypt-1.0.0

**Comment by scara** [comment]
Hi @vsotirasqmplus,
IIUC this issue should be filed on https://github.com/moodlehq/moodle-php-apache/.

BTW what is your use case?
`mcrypt` has been [deprecated](https://www.php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt).

HTH,
Matteo

**Comment by vsotirasqmplus** [comment]
Hi,

Thanks for the message.

We still have to support some abandoned 3rd party plugins for our institution so having mcrypt will be useful for the transition development

Sincerely



Vasileios Sotiras

e-Learning Systems Development Analyst

Information Technology Services

Queen Mary University of London

Rm TB.102, Mile End, London, E1 4NS

Tel:  +44 (0) 20 7882 6926

Email: v.sotiras@qmul.ac.uk



Like numbers? Check these ones out - QMUL ITS Statistics<http://www.its.qmul.ac.uk/support/statistics/index.html>



Queen Mary is committed to reducing its carbon footprint.  Please only print this email if absolutely necessary.


[cid:d3cd525c-4da7-41ff-a9bb-bbcd445f5369]

________________________________

**Comment by vsotirasqmplus** [comment]
docker exec -it moodle-docker_webserver_1 bash -c "pecl install mcrypt-1.0.0 <</dev/null"
docker exec -it moodle-docker_webserver_1 bash -c "echo extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mcrypt.so >> /usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini"
docker exec -it moodle-docker_webserver_1 apachectl graceful
